databaseChangeLog:
- changeSet:
    id: create customer
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_5
            name: ID
            type: BIGINT
        - column:
            name: LAST_NAME
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: FIRST_NAME
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: ADDRESS
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: ZIP_CODE
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: CITY
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: COUNTRY
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: PHONE
            constraints:
              nullable: false
            type: VARCHAR(255)
        tableName: CUSTOMER
- changeSet:
    id: create pet
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_1
            name: ID
            type: BIGINT
        - column:
            name: NAME
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: SPECIES_ID
            constraints:
              nullable: false
            type: BIGINT
        - column:
            name: PRICE
            constraints:
              nullable: false
            type: DECIMAL
        tableName: PET
- changeSet:
    id: create purchase
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_9
            name: ID
            type: BIGINT
        - column:
            name: DATE
            constraints:
              nullable: false
            type: TIMESTAMP
        - column:
            name: CUSTOMER_ID
            constraints:
              nullable: false
            type: BIGINT
        - column:
            name: PET_ID
            constraints:
              nullable: false
            type: BIGINT
        tableName: PURCHASE
- changeSet:
    id: create species
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_B
            name: ID
            type: BIGINT
        - column:
            name: NAME
            type: VARCHAR(255)
        tableName: SPECIES

- changeSet:
    id: create user
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_10
            name: ID
            type: BIGINT
        - column:
            name: NAME
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: PASSWORD
            constraints:
              nullable: false
            type: VARCHAR(255)
        - column:
            name: EMAIL
            constraints:
              nullable: false
            type: VARCHAR(255)
        tableName: USER
- changeSet:
    id: create preferences
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_11
            name: ID
            type: BIGINT
        - column:
            name: DARK_MODE
            defaultValueBoolean: false
            constraints:
              nullable: false
            type: BOOLEAN
        - column:
            name: USER_ID
            constraints:
              nullable: false
            type: BIGINT
        tableName: PREFERENCES

- changeSet:
    id: create purchase to customer index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: CUSTOMER_ID
        indexName: FK_PURCHASE_TO_CUSTOMER_INDEX
        tableName: PURCHASE
- changeSet:
    id: create pet to species index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: SPECIES_ID
        indexName: FK_PETTOSPECIES_INDEX
        tableName: PET
- changeSet:
    id: create purchae to pet index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: PET_ID
        indexName: FK_PURCHASETOPET
        tableName: PURCHASE
- changeSet:
    id: create purchase to customer fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: CUSTOMER_ID
        baseTableName: PURCHASE
        constraintName: FK_CUSTOMERTOPET
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: CUSTOMER
        validate: true
- changeSet:
    id: create pet to species fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: SPECIES_ID
        baseTableName: PET
        constraintName: FK_PETTOSPECIES
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: SPECIES
        validate: true
- changeSet:
    id: create purchase to pet fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: PET_ID
        baseTableName: PURCHASE
        constraintName: FK_PURCHASETOPET
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: PET
        validate: true

- changeSet:
    id: load data
    author: petstore
    changes:
    - loadData:
        file: species.tsv
        relativeToChangelogFile: true
        separator: '	'
        quotchar: ''''
        tableName: SPECIES
    - loadData:
          file: pet.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: PET
    - loadData:
          file: customer.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: CUSTOMER
    - loadData:
          file: purchase.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: PURCHASE
    - loadData:
          file: user.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: USER
    - loadData:
          file: preferences.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: PREFERENCES